### PR TITLE
Add rake tasks

### PR DESCRIPTION
**Pull request by rramsden**
## Context

I noticed rails_drivers does not load rake files for drivers. This pull request loads rake task files from a driver.

Unfortunately, I was unable to load Rake tasks inside the driver initializers folder since these hooks are loaded before booting up Rails and not Rake.

### CODE REVIEW

**Comment by rramsden** [comment]
@Resonious Could you take a look? I'm not sure the best way of writing a test for this one. Also, not sure if we want to load task definitions using the Railtie module.

**Comment by Resonious** [comment]
Looks good! The test you wrote works fine. If you want, you could do `expect { run_command "blahblah" }.to_not raise_error` to be more explicit about what the expectation is, but it's true that `run_command` will fail on non-zero exit status anyway.

If we want to auto-namespace the tasks, you should be able to wrap the `load` call in a call to `namespace` since it's just loading ruby code. Something like 

```ruby
Dir['drivers/*/lib/tasks/**/*.rake'].each do |driver_rake_file|
  %r{^drivers/(?<driver_name>\w+)/} =~ driver_rake_file
  namespace(:driver) { namespace(driver_name) { load(driver_rake_file) } }
end
```
should work I think.

**Comment by rramsden** [comment]
@Resonious Okay, here are my new changes:

* Wrapped rake tasks in a namespace as per your suggestion
* Wrapped test asserts in `.to_not raise_error`
* Added `lib/tasks/.keep` to the generator
* Updated the project README to explain auto-namespacing.

**Comment by Resonious** [comment]
All looks good. Last thing is to bump version.rb. I guess this would be a minor version since it adds functionality.

**Comment by rramsden** [comment]
Okay, bumped the version.

**Comment by rramsden** [comment]
Okay, bumped.

**Comment by Resonious** [comment]
Okay should be live on rubygems now! https://github.com/degica/rails_drivers/commit/ecc0ed35a98d6938d2c8a0afc328c861585b9c0f/checks?check_suite_id=399276884

**Pull request merged**
